### ISSUE TITLE
[TASK] Admin category editor page

### ISSUE THREAD

**Issue by BeatsuDev** [BeatsuDev/let#19]
# Task description
An admin should be able to create categories. (editing and deleting can be added later. Create separate issues for this)

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] A new category editor page
- [x] Only admins must be able to create categories
- [x] Must add category through backend REST API

## Task dependencies
This task requires these tasks to be completed:
None
