### ISSUE TITLE
[TASK] Filter items for sale by category

### ISSUE THREAD

**Issue by BeatsuDev** [BeatsuDev/let#2]
# Task description
Every item must be part of a category. Every category should be shown as a list view next to the items for sale grid/list. Users must be able to check multiple categories. When multiple categories are checked, items from any of those categories should be shown.

## Task Completion Requirements
These requirements must be fulfilled for this issue to be closed / for the task to be considered finished.
- [x] The item list page must have a listview of categories to be chosen from.
- [x] Only items with any of the checked categories must be shown.
- [ ] Users must be able to check multiple categories.

## Task dependencies
This task requires these tasks to be completed:
- #1
